name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Rename APK
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/pokemons.apk

      - name: Upload APK to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: debug
          path: app/build/outputs/apk/debug/pokemons.apk

  post-build:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout io repository
        uses: actions/checkout@v2
        with:
          repository: 'alad1nks/alad1nks.github.io'
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: debug
          path: pokemons

      - name: Commit APK
        run: |
          git config --local user.name 'alad1nks'
          git config --local user.email 'alad1nks@users.noreply.github.com'
          git add pokemons/*.apk
          git commit -m 'Add generated APK file'
          git push
